### PR TITLE
Added reSplit

### PR DESCRIPTION
**Pull request by BlackWolfWoof**
I bet more stuff is missing but I will just pr it if i see it is missing

### CODE REVIEW

**Comment by SpecialEliteSNP** [comment]
Is there a new update? I haven't checked it lately. Please PR it if it's missing, thanks.

**Comment by BlackWolfWoof** [comment]
Before you merge i'll add something new

**Comment by SpecialEliteSNP** [comment]
@BlackWolfWoof You've removed reSplit again, did you mean to do that?

**Comment by BlackWolfWoof** [comment]
> 
> 
> @BlackWolfWoof You've removed reSplit again, did you mean to do that?

uhhhhhhhh frick, nope wasn't planned xd

**Comment by BlackWolfWoof** [comment]
could you fix it pls xd haha kms

**Comment by SpecialEliteSNP** [comment]
I can't be asked optimizing that regex again 😅. I'm going to merge this now. Thank you @BlackWolfWoof

**Comment by BlackWolfWoof** [comment]
haha thanks

**Comment by SpecialEliteSNP** [comment]
whoops

**Comment by BlackWolfWoof** [comment]
>  can't be asked optimizing that regex again 😅

Yea i saw bruh lol

**Comment by BlackWolfWoof** [comment]
> whoops

Lol you closed without mergin? Ah now u did, xd ty

**Comment by SpecialEliteSNP** [comment]
haha yeah mb

**Pull request merged**
