### PR TITLE
Added .gotmpl to package.json

### PR DESCRIPTION
**Pull request by BlackWolfWoof**
Pls xd, it is killing me always having to change the language. And my entire github custom commands are all .gotmpl

### CODE REVIEW

**Comment by SpecialEliteSNP** [comment]
Haha well the only reason I didn't add it is because YAGPDB custom commands don't have full Go Template support. But if I'm going to add it, I might as well add .go.tmpl too.

**Comment by BlackWolfWoof** [comment]
UwU ty :3

**Comment by BlackWolfWoof** [comment]
Oh yea if you do actually add it make sure to also change it in the readme. Because as far as i have seen after creating the pr is that you use the pr on the vsc marketplace too

**Comment by SpecialEliteSNP** [comment]
I've looked into creating a setting for the extension to enable or disable the support. Unfortunately I can't make the extensions file extension variable... I will update the readme with a guide on how to add the extensions manually to the package.json.

**Comment by SpecialEliteSNP** [comment]
@BlackWolfWoof if this is all cool with you, I'd like to merge this PR

**Comment by BlackWolfWoof** [comment]
Hmm... thats how i did it before but every update it keeps changing back and i haven't found a way to disable updates for only one extension. 
It's ok with me if you close (or merge) the pr and won't add the gotmpl to the file ofc and i will keep having to do it manually and maybe i'll switch over to another file extension some day.

**Comment by SpecialEliteSNP** [comment]
Well I'm not going to update it very often so don't worry too much about that. Also the process of doing it isn't that hard and maybe you should just make the switch to `.yag` 👀 😉

**Comment by BlackWolfWoof** [comment]
> Well I'm not going to update it very often so don't worry too much about that. Also the process of doing it isn't that hard and maybe you should just make the switch to `.yag` 👀 😉 

I'd basically have to change everything... Which will break several snippets on the yag server, old links and more sooo uhhh yea

**Pull request merged**
